from .register import RegisterView # noqa
from .login import LoginView # noqa
from .users import UserViewSet # noqa
from .user_by_name import UserByNameView # noqa
from .change_password import ChangePasswordView # noqa
from .change_password_confirm import ChangePasswordConfirmView # noqa
from .logout import LogoutView # noqa
from .profile import ProfileViewSet # noqa
from .confirm_register import ConfirmRegisterView # noqa
from .forgot_password import ForgotPasswordView # noqa
